### ISSUE TITLE
[FEAT] 날씨 보여주는 View 와 Detail view 구현

### ISSUE THREAD

**Issue by Genesis2010** [DO-SOPT-iOS-Part/ParkJunHyuk-assignment#3]
## 💡 Issue
SF Pro Display Font 를 추가하고 날씨 데이터를 보여주는 View 와 Deatil ViewController 를 구현합니다.

<br>

## 📝  todo
- [x] SF Pro Display Font 추가
- [x] 날씨 데이터를 보여주는 View 구현
- [x] 자세한 날씨 정보를 보여주는 ViewController 구현

<br>

## 📸 Screenshot

|MainView|DetailView|
|------|------|
|<img width="300" alt="Weather_5" src="https://github.com/DO-SOPT-iOS-Part/ParkJunHyuk-assignment/assets/45564605/7568290d-19a6-4640-90da-84c318c4d6ee">|<img width="300" alt="Weather_1" src="https://github.com/DO-SOPT-iOS-Part/ParkJunHyuk-assignment/assets/45564605/b333a549-422f-466e-bc5f-9795c1726e86">|
