### ISSUE TITLE
[FEAT] 3주차 과제 - Table, Collection View 를 이용한 10일 간의 일기 예보 View 구현

### ISSUE THREAD

**Issue by Genesis2010** [DO-SOPT-iOS-Part/ParkJunHyuk-assignment#5]
## 💡 Issue
기존의 StackView 로 구현 되어있던 View 를 TableView, CollectionView 를 이용하여 10일 간의 일기 예보 View 를 구현합니다. 

## 📝  todo
- [ ] StackView 를 TableView, CollectionView 로 변경
- [ ] 10일 간의 일기 예보 View 구현
- [ ] 그라디언트 뷰 구현 ( 심화 과제 )
- [ ] 스크롤시 동적으로 변화하는 View 구현 ( 심화과제 )

## 📸 Screenshot
|10일간 일기예보 View|
|---|
|<img width="300" alt="" src="https://github.com/DO-SOPT-iOS-Part/ParkJunHyuk-assignment/assets/45564605/312f1ad1-efac-4250-8823-d7f03397e5ac">|
